import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import path from 'node:path';
const frame = JSON.stringify({jsonrpc:'2.0', id:1, payload:'HAPAtlas — العربية ' + 'x'.repeat(80000)});
const process = spawn('powershell.exe', ['-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',path.join(import.meta.dirname,'stdio-relay-fixture.ps1')], {windowsHide:true, stdio:['pipe','pipe','pipe']});
let stdout = '', stderr = '';
process.stdout.setEncoding('utf8');
process.stderr.setEncoding('utf8');
process.stdout.on('data', part => {stdout += part;});
process.stderr.on('data', part => {stderr += part;});
const timer = setTimeout(() => {process.kill(); throw new Error('Stdio relay timed out');}, 20000);
process.stdin.write(frame.slice(0,23));
process.stdin.end(frame.slice(23) + '\n');
const code = await new Promise((resolve,reject) => {process.on('exit',resolve); process.on('error',reject);});
clearTimeout(timer);
assert.equal(code,7,stderr);
assert.equal(stdout.trimEnd(),frame);
assert.equal(stderr.trim(),'stderr-only-marker');
console.log('PASS byte-stream relay: fragmented UTF-8, large payload, stderr separation, exit status');
